djangoTest2/test4/booktest/urls.py
from django.urls import re_path

from booktest import views

urlpatterns = [
    re_path(r'^index2$', views.index,name='index'),  # 首页
    re_path(r'^temp_var$', views.temp_var),  # 测试模板变量
    re_path(r'^temp_tags$', views.temp_tags),  # 模板标签
    re_path(r'^temp_filter$', views.temp_filter),  # 模板过滤器
    re_path(r'^temp_inherit$', views.temp_inherit),  # 模板继承
    re_path(r'^temp_myfilter$', views.temp_myfilter),  # 自定义过滤器
    re_path(r'^login_check$', views.login_check),
    re_path(r'^login$', views.login),
    re_path(r'^change_pwd$',views.change_pwd),#修改密码
    re_path(r'^change_pwd_action$',views.change_pwd_action),#修改密码并返回
    re_path(r'^verify_code$',views.verify_code),#生成验证码
    re_path(r'^url_reverse$',views.url_reverse),#验证url反向解析
    re_path(r'^url_reverses/(\d+)/(\d+)$',views.url_reverses,name='url_re'),#带参数的url反向解析
    re_path(r'^view_reverse$',views.view_reverse),#视图层的反向解析
]

djangoTest2/test4/test4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('booktest.urls','booktest'),namespace='booktest'))#用于url反向解析
]

djangoTest2/test4/booktest/models.py
from django.db import models


# Create your models here.
class BookInfo(models.Model):
    btitle = models.CharField(max_length=30)
    bpub_date = models.DateField()
    bread = models.IntegerField(default=0)
    bcomment = models.IntegerField(default=0)
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        return self.btitle


class HeroInfo(models.Model):
    hname = models.CharField(max_length=60)
    hgender = models.BooleanField(default=False)
    hcomment = models.CharField(max_length=80)
    hbook = models.ForeignKey('BookInfo', on_delete=models.CASCADE)
    isDelete = models.BooleanField(default=False, null=True, blank=True)

    def __str__(self):
        return self.hname


class AreaInfo(models.Model):
    # 设置地区名称
    atitle = models.CharField(max_length=30)
    # 设置自关联
    aparent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)

djangoTest2/test4/booktest/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.template import loader, RequestContext
from django.urls import reverse
from booktest.models import BookInfo


# Create your views here.
def index(request):
    # 定义加载模板文件
    temp = loader.get_template('booktest/index.html')
    # 导入模板文件,加载数据
    context = RequestContext(request, {})
    context.push(locals())
    # 渲染模板文件
    render_html = temp.render(context=locals(), request=request)
    return HttpResponse(render_html)


# 测试模板变量 可以是字典，列表和对象
def temp_var(request):
    my_dict = {"btitle": "man"}
    my_list = [1, 23, 4]
    book = BookInfo.objects.get(id=1)
    context = {"my_dict": my_dict, "my_list": my_list, "book": book}
    return render(request, 'booktest/temp_var.html', context)


# 模板标签
def temp_tags(request):
    books = BookInfo.objects.all()
    return render(request, 'booktest/temp_tags.html', {'books': books})


# 模板过滤器filter
def temp_filter(request):
    books = BookInfo.objects.all()
    return render(request, 'booktest/temp_filter.html', {'books': books})


# 模板继承
def temp_inherit(request):
    return render(request, 'booktest/child.html', {})


# 自定义模板过滤器
def temp_myfilter(request):
    list = [1, 6, 3, 9, 8, 2]
    temp = loader.get_template('booktest/temp_myfilter.html')
    context = RequestContext(request, {'list': list})
    context.push(locals())
    render_html = temp.render(context=locals(), request=request)
    return HttpResponse(render_html)

#装饰器 主要是用来判断是不是在线状态
def login_required(func):
    def loginTest(request,*args,**kwargs):
        if  request.session.has_key('islogin'):
            return func(request,*args,**kwargs)
        else:
            return redirect('/login')
    return loginTest

def login(request):
    if request.session.has_key('islogin'):
        return redirect('/change_pwd')
    else:
        if 'username' in request.COOKIES:
            username = request.COOKIES['username']
        else:
            username = ''
        return render(request, 'booktest/login.html', {'username': username})


def login_check(request):
    username = request.POST.get('username')
    password = request.POST.get('password')
    remember = request.POST.get('remember')
    code1=request.POST.get('code1')#这个时用户输入的验证码
    print(code1)
    code2=request.session.get('verifycode')#这个时存储在session里面的验证码
    print(code2)
    if code1 != code2:
        return redirect('/login')

    if username == 'man' and password == '123':
        response = redirect('/change_pwd')
        if remember == 'on':
            response.set_cookie('username', username, max_age=2 * 24 * 3600)
        request.session['islogin'] = True
        request.session['username']=username#获取session的用户名，永久保存
        return response
    else:
        return redirect('/login')

  #修改密码
@login_required
def change_pwd(request):
    return render(request,'booktest/change_pwd.html',{})
#修改密码返回
@login_required
def change_pwd_action(request):
    #获取修改密码后的密码并返回
    pwd=request.POST.get('pwd')
    username=request.session.get('username')#通过session获得的
    return HttpResponse("%s修改密码后为:%s"%(username,pwd))

#验证码生成
from PIL import Image, ImageDraw, ImageFont
from django.utils.six import BytesIO
def verify_code(request):
    # 引入随机函数模块
    import random
    # 定义变量，用于画面的背景色、宽、高 RGB
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 25
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)

    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]

    # 构造字体对象，ubuntu的字体路径为“C:\Users\MACHENLKE\Desktop\djangoTest2\FreeMono.ttf”
    font = ImageFont.truetype(r'C:\Users\MACHENLKE\Desktop\djangoTest2\FreeMono.ttf', 23)
    # 构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    print(rand_str)
    request.session['verifycode'] = rand_str
    # 内存文件操作
    buf = BytesIO()
    # 将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')

#url反向解析
def url_reverse(request):
    return render(request,'booktest/url_reverse.html',{})

#url反向解析带参数
def url_reverses(request,a,b):
    return HttpResponse(a+b)

#视图层的反向解析，其他带参数的参考上面或者上网搜，args,kwargs都是针对带参数的
def view_reverse(request):
    url=reverse('booktest:index')
    return redirect(url)

djangoTest2/test4/booktest/templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模板继承</title>
</head>
<body>
<h1>标题</h1>
<h3>横杆</h3>
{% block b1 %}
    <h6>李慢</h6>
{% endblock %}
</body>
</html>

djangoTest2/test4/booktest/templates/booktest/change_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
<form method="post" action="/change_pwd_action">
    {% csrf_token %}
    新密码：<input type="password" name="pwd"></br>
    <input type="submit" value="提交">
</form>
</body>
</html>

djangoTest2/test4/booktest/templates/booktest/child.html
{% extends 'booktest/base.html' %}
{% block b1 %}
    <h1>这是子模版</h1>{# 这个是可以替换base.html中指定区域的内容 #}
    {{ block.super }}  {# 这个是可以指定加载base.html中的内容 #}
{% endblock b1 %}

djangoTest2/test4/booktest/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
<h1>首页</h1>
</body>
</html>

djangoTest2/test4/booktest/templates/booktest/login.html
<!DOCTYPE html>
<br lang="en">
<head>
    <meta charset="UTF-8">
    <title>模板文件</title>

   {% comment %} <script src="/static/js/jquery-1.12.4.min.js"></script>{% endcomment %}

        {% comment %} <script>

  $(function () {
            $('#loginAjax').click(function () {
                username = $('#username').val();
                password = $('#password').val();
                $.ajax({
                    'url': 'login_check',
                    'type': 'post',//请求方式
                    'data': {'username': username, 'password': password},//Ajax返回参数，返回用户信息
                    'dataType': 'json',
                }).success(function (data) {
                    if (data.res == 0) {//如果登陆失败，返回
                        $('#message').show().html("用户名或者密码错误")
                    } else {//如果登陆成功返回到主页
                        location.href = "/index"
                    }


                })
            })
        })

</script>

    <style>
        #message {
            display: none;
            color: red;

        }
    </style>{% endcomment %}

</head>
<form method="post" action="/login_check">
    {% csrf_token %}{% comment %}csrf_token的防护措施 跨站请求修改密码{% endcomment %}
    用户名:<input type="text" name="username" value="{{ username }}"><br>
    密码:<input type="password" name="password"><br>
    <input type="checkbox" name="remember">记住用户名<br>
{% comment %}直接访问验证码url会直接显示图片，当然可以调整验证码图片大小，这个是前端的事情{% endcomment %}
    <img src="/verify_code"><input type="text" name="code1"><br>
    <input type="submit"  value="登陆">
{% comment %}<div id="message"></div>{% endcomment %}
</form>


</body>
</html>

djangoTest2/test4/booktest/templates/booktest/temp_filter.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>模板filter</title>
    <style>
        .red {
            background-color: blueviolet;
        }

        .green {
            background-color: green;
        }

    </style>
</head>
<body>
<ul>
    {% for book in books %}
        {% if book.id <= 3 %}
            <li class="red">{{ book.btitle }}---{{ book.bpub_date | date:'Y年-m月-d日' }}</li>
        {% elif book.id <= 4 %}
            <li class="orange">{{ book.btitle }}--{{ book.bpub_date | date:'Y年-m月-d日' }}</li>
        {% else %}
            <li class="green">{{ book.btitle }}--{{ book.bpub_date | date:'Y年-m月-d日' }}</li>
        {% endif %}
    {% endfor %}
</ul>

</body>
</html>

djangoTest2/test4/booktest/templates/booktest/temp_myfilter.html
{% load filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>过滤器</title>
</head>
<style>
    .red {
        background-color: red;
    }
</style>
<body>
{% for i in list %}
    {% if i|filter %}
        <li class="red">{{ i }}</li>
    {% endif %}

{% endfor %}
</body>
</html>

djangoTest2/test4/booktest/templates/booktest/temp_tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模板标签</title>
    <style>
        .red {
            background-color: blueviolet;
        }

        .green {
            background-color: green;
        }

        .orange {
            background-color: orange;
        }
    </style>
</head>
<body>
<ul>
    {% for book in books %}
        {% if book.id <= 3 %}
            <li class="red">{{ forloop.counter }}----{{ book.btitle }}</li>
        {% elif book.id <= 4 %}
            <li class="orange">{{ forloop.counter }}---{{ book.btitle }}</li>
        {% else %}
            <li class="green">{{ forloop.counter }}---{{ book.btitle }}</li>
        {% endif %}
    {% endfor %}
</ul>
</body>
</html>

djangoTest2/test4/booktest/templates/booktest/temp_var.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>模板文件</title>
</head>
<body>
我的字典:{{ my_dict.btitle }}
我的列表:{{ my_list.1 }}
BookInfo:{{ book.btitle }}
</body>
</html>

djangoTest2/test4/booktest/templates/booktest/url_reverse.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>url反向解析</title>
</head>
<body>
<a href="index.html">点击</a>
{% comment %}url反向解析，booktest指urls.py默认的namespace,index指新建的urls.py里面的name
,这样配置无论你以前的index主页的名称怎么改动都不会影响项目的所有名字的改变{% endcomment %}
<a href="{% url 'booktest:index' %}">点击</a>

<a href="{% url 'booktest:url_re' 1 2 %}">url带参数</a>
</body>
</html>